tags = []

[[devices]]
appearance = ""
column1 = "0D"
column2 = ""
company_logo = ""
device_code = ""
device_name = "智慧养老智能主机V40"
id = "1"
identifier = "55"
manufacturer = "安徽三联机器人科技有限公司"
product_model = "SLR-ZG300-32-01"
production_category = "01"
production_type = "A001"
production_week = ""
production_year = ""
qr_code_content = ""

[[devices]]
appearance = "33"
column1 = "0C"
column2 = ""
company_logo = ""
device_code = ""
device_name = "独立式可燃气体智能探测器"
id = "2"
identifier = "55"
manufacturer = "安徽三联机器人科技有限公司"
product_model = "SLR-DS-CG33-32-1"
production_category = "01"
production_type = "A201"
production_week = ""
production_year = ""
qr_code_content = ""

[[devices]]
appearance = "52"
column1 = "0C"
column2 = ""
company_logo = ""
device_code = ""
device_name = "独立式烟雾智能探测器"
id = "3"
identifier = "55"
manufacturer = "安徽三联机器人科技有限公司"
product_model = "SLR-DS-SA52-32-1"
production_category = "01"
production_type = "A401"
production_week = ""
production_year = ""
qr_code_content = ""

[[devices]]
appearance = "04"
column1 = "0C"
column2 = ""
company_logo = ""
device_code = ""
device_name = "独立式人体智能感应器"
id = "4"
identifier = "55"
manufacturer = "安徽三联机器人科技有限公司"
product_model = "SLR-DS-IB04-32-1"
production_category = "02"
production_type = "A701"
production_week = ""
production_year = ""
qr_code_content = ""

[[devices]]
appearance = ""
column1 = "0C"
column2 = ""
company_logo = ""
device_code = ""
device_name = "独立式侧装语音人体智能感应器"
id = "5"
identifier = "55"
manufacturer = "安徽三联机器人科技有限公司"
product_model = ""
production_category = "02"
production_type = "A702"
production_week = ""
production_year = ""
qr_code_content = ""

[[devices]]
appearance = "03"
column1 = "0C"
column2 = ""
company_logo = ""
device_code = ""
device_name = "独立式门磁智能传感终端"
id = "6"
identifier = "55"
manufacturer = "安徽三联机器人科技有限公司"
product_model = "SLR-BS-GM03-32-1"
production_category = "02"
production_type = "A801"
production_week = ""
production_year = ""
qr_code_content = ""

[[devices]]
appearance = "18"
column1 = "0C"
column2 = ""
company_logo = ""
device_code = ""
device_name = "独立式呼叫求助器"
id = "7"
identifier = "55"
manufacturer = "安徽三联机器人科技有限公司"
product_model = "SLR-BS-CA18-32-1"
production_category = "02"
production_type = "AB01"
production_week = ""
production_year = ""
qr_code_content = ""

[[devices]]
appearance = "39"
column1 = "0C"
column2 = ""
company_logo = ""
device_code = ""
device_name = "独立式语音呼叫求助器"
id = "8"
identifier = "55"
manufacturer = "安徽三联机器人科技有限公司"
product_model = "SLR-BS-CA39-32-1"
production_category = "02"
production_type = "AB02"
production_week = ""
production_year = ""
qr_code_content = ""

[[devices]]
appearance = "88"
column1 = "0C"
column2 = ""
company_logo = ""
device_code = ""
device_name = "独立式体征监测智能传感带"
id = "9"
identifier = "55"
manufacturer = "安徽三联机器人科技有限公司"
product_model = "SLR-DS-VS88-32-1"
production_category = "01"
production_type = "AC01"
production_week = ""
production_year = ""
qr_code_content = ""

[[devices]]
appearance = "33"
column1 = "0C"
column2 = ""
company_logo = ""
device_code = ""
device_name = "独立式跌倒探测雷达终端"
id = "10"
identifier = "55"
manufacturer = "安徽三联机器人科技有限公司"
product_model = "SLR-DS-FR33-32-1"
production_category = "01"
production_type = "AE01"
production_week = ""
production_year = ""
qr_code_content = ""

[[devices]]
appearance = "02"
column1 = "0C"
column2 = ""
company_logo = ""
device_code = ""
device_name = "独立式水浸传感器"
id = "11"
identifier = "55"
manufacturer = "安徽三联机器人科技有限公司"
product_model = "SLR-BS-WMO2-32-1"
production_category = "02"
production_type = "A901"
production_week = ""
production_year = ""
qr_code_content = ""

[[devices]]
appearance = ""
column1 = "0C"
column2 = ""
company_logo = ""
device_code = ""
device_name = "天然气体智能探测器"
id = "12"
identifier = "55"
manufacturer = "安徽三联机器人科技有限公司"
product_model = ""
production_category = "01"
production_type = "0101"
production_week = ""
production_year = ""
qr_code_content = ""

[[devices]]
appearance = "33"
column1 = "0C"
column2 = ""
company_logo = ""
device_code = ""
device_name = "可燃气体智能探测器"
id = "13"
identifier = "55"
manufacturer = "安徽三联机器人科技有限公司"
product_model = "SLR-DS-CG33-32-1"
production_category = "01"
production_type = "0201"
production_week = ""
production_year = ""
qr_code_content = ""

[[devices]]
appearance = ""
column1 = "0C"
column2 = ""
company_logo = ""
device_code = ""
device_name = "一氧化碳智能探测器"
id = "14"
identifier = "55"
manufacturer = "安徽三联机器人科技有限公司"
product_model = ""
production_category = "01"
production_type = "0301"
production_week = ""
production_year = ""
qr_code_content = ""

[[devices]]
appearance = "52"
column1 = "0C"
column2 = ""
company_logo = ""
device_code = ""
device_name = "烟雾智能探测器"
id = "15"
identifier = "55"
manufacturer = "安徽三联机器人科技有限公司"
product_model = "SLR-DS-SA52-32-1"
production_category = "01"
production_type = "0401"
production_week = ""
production_year = ""
qr_code_content = ""

[[devices]]
appearance = "07"
column1 = "0C"
column2 = ""
company_logo = ""
device_code = ""
device_name = "空气质量监测器"
id = "16"
identifier = "55"
manufacturer = "安徽三联机器人科技有限公司"
product_model = "SLR-DS-AQ07-32-1"
production_category = "01"
production_type = "0501"
production_week = ""
production_year = ""
qr_code_content = ""

[[devices]]
appearance = "04"
column1 = "0C"
column2 = ""
company_logo = ""
device_code = ""
device_name = "人体智能感应器"
id = "17"
identifier = "55"
manufacturer = "安徽三联机器人科技有限公司"
product_model = "SLR-DS-IB04-32-1"
production_category = "02"
production_type = "0701"
production_week = ""
production_year = ""
qr_code_content = ""

[[devices]]
appearance = ""
column1 = "0C"
column2 = ""
company_logo = ""
device_code = ""
device_name = "侧装语音人体智能感应器"
id = "17"
identifier = "55"
manufacturer = "安徽三联机器人科技有限公司"
product_model = ""
production_category = "02"
production_type = "0702"
production_week = ""
production_year = ""
qr_code_content = ""

[[devices]]
appearance = "03"
column1 = "0C"
column2 = ""
company_logo = ""
device_code = ""
device_name = "门磁智能传感终端"
id = "18"
identifier = "55"
manufacturer = "安徽三联机器人科技有限公司"
product_model = "SLR-BS-GM03-32-1"
production_category = "02"
production_type = "0801"
production_week = ""
production_year = ""
qr_code_content = ""

[[devices]]
appearance = "02"
column1 = "0C"
column2 = ""
company_logo = ""
device_code = ""
device_name = "水浸智能监测器"
id = "19"
identifier = "55"
manufacturer = "安徽三联机器人科技有限公司"
product_model = "SLR-BS-WS03-32-1"
production_category = "02"
production_type = "0901"
production_week = ""
production_year = ""
qr_code_content = ""

[[devices]]
appearance = "18"
column1 = "0C"
column2 = ""
company_logo = ""
device_code = ""
device_name = "呼叫求助器"
id = "20"
identifier = "55"
manufacturer = "安徽三联机器人科技有限公司"
product_model = "SLR-BS-CA18-32-1"
production_category = "02"
production_type = "0B01"
production_week = ""
production_year = ""
qr_code_content = ""

[[devices]]
appearance = "39"
column1 = "0C"
column2 = ""
company_logo = ""
device_code = ""
device_name = "语音呼叫求助器"
id = "21"
identifier = "55"
manufacturer = "安徽三联机器人科技有限公司"
product_model = "SLR-BS-CA39-32-1"
production_category = "01"
production_type = "0B02"
production_week = ""
production_year = ""
qr_code_content = ""

[[devices]]
appearance = "88"
column1 = "0C"
column2 = ""
company_logo = ""
device_code = ""
device_name = "体征监测智能传感带"
id = "22"
identifier = "55"
manufacturer = "安徽三联机器人科技有限公司"
product_model = "SLR-DS-VS88-32-1"
production_category = "01"
production_type = "0C01"
production_week = ""
production_year = ""
qr_code_content = ""

[[devices]]
appearance = "33"
column1 = "0C"
column2 = ""
company_logo = ""
device_code = ""
device_name = "睡眠监测雷达终端"
id = "23"
identifier = "55"
manufacturer = "安徽三联机器人科技有限公司"
product_model = ""
production_category = "01"
production_type = "0D01"
production_week = ""
production_year = ""
qr_code_content = ""

[[devices]]
appearance = "33"
column1 = "0C"
column2 = ""
company_logo = ""
device_code = ""
device_name = "跌倒探测雷达终端"
id = "24"
identifier = "55"
manufacturer = "安徽三联机器人科技有限公司"
product_model = "SLR-DS-FR33-32-1"
production_category = "01"
production_type = "0E01"
production_week = ""
production_year = ""
qr_code_content = ""

[[devices]]
appearance = ""
column1 = "0C"
column2 = ""
company_logo = ""
device_code = ""
device_name = "双向提醒器"
id = "25"
identifier = "55"
manufacturer = "安徽三联机器人科技有限公司"
product_model = ""
production_category = "01"
production_type = "1001"
production_week = ""
production_year = ""
qr_code_content = ""

[[devices]]
appearance = ""
column1 = "0C"
column2 = ""
company_logo = ""
device_code = ""
device_name = "单向提醒器"
id = "26"
identifier = "55"
manufacturer = "安徽三联机器人科技有限公司"
product_model = ""
production_category = "01"
production_type = "1002"
production_week = ""
production_year = ""
qr_code_content = ""

[gateway]
ble_mode_check = false
blecard_init_check = false
blecard_recv_check = false
nvs_check = false
onboard_sensor_check = false
online_check = false
recv_sensor_check = false

[independent]
ble_mode_check = false
nvs_check = false
online_check = false
send_data_check = false

[sensor]
ble_mode_check = false
config_to_gateway = false
nvs_check = false
send_data_check = false
